<?php
/**
* Admin functionality
*
* @author  Nic Durish
*/

// Prevent direct file access.
if ( ! defined( 'WCAGQF_FILE' ) ) {
	die();
}

/**
* Determine if WP's CodeMirror is available.
*
* As CodeMirror was added in ver 4.9, simply compare with the
* current WP version.
*
* @since 1.0.0
* @return bool
*/
function wcagqf_wp_codemirror_available() {
  $wp_version = get_bloginfo( 'version' );
  return ( version_compare( $wp_version, 4.9 ) >= 0 );
}

/**
* Print direct link to settings page from plugin menu
*
* Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
* and inserts a link to the Custom CSS admin page
*
* @since  1.0.0
* @filter plugin_action_links_
*/
function css_settings_link( $links ) {
  return array_merge(
    array(
      'settings' => '<a href="' . admin_url( 'options-general.php?page=wcag_quickfix_js_settings' ) . '">' . __( 'JS', 'WCAG' ) . '</a>'
    ),
    array(
    	'settings2' => '<a href="' . admin_url( 'options-general.php?page=wcag_quickfix_css_settings' ) . '">' . __( 'CSS', 'WCAG' ) . '</a>'
    ),
    $links
  );
}
add_filter( 'plugin_action_links_' . plugin_basename( WCAGQF_FILE ), 'css_settings_link' );

/**
* Delete file when plugin is uninstalled
*
* @since 1.0.0
*/
function css_uninstall() {
  delete_option( WCAGQF_OPTION );
}
register_uninstall_hook( WCAGQF_FILE, 'css_uninstall' );

/**
 * Enqueues Scripts/Styles for Syntax Highlighter.
 *
 */
function wcagqf_register_codemirror( $hook ) {
	if ( wcagqf_wp_codemirror_available() ) {
		wp_enqueue_code_editor( array( 'type' => 'text/html' ) );
		wp_enqueue_script( 'wcagqf-editor-css', plugins_url( 'gds-wcag-quickfixes/includes/js/editorcss.js' ), array( 'jquery' ), '', true );
    wp_enqueue_script( 'wcagqf-editor-js', plugins_url( 'gds-wcag-quickfixes/includes/js/editorjs.js' ), array( 'jquery' ), '20190307', true );
	}
}
add_action( 'admin_enqueue_scripts', 'wcagqf_register_codemirror' );

/**
* Register "WCAG Quickfixes" submenu in "Settings" Admin Menu.
*
* @since  1.0.0
* @action admin_menu
*/
function wcagqf_setup_menu(){
   add_submenu_page( 'options-general.php', 'WCAG Quickfix CSS Settings', 'CSS WCAG Quickfixes', 'manage_options', 'wcag_quickfix_css_settings', 'wcag_quickfix_settings_css_content' );
   add_submenu_page( 'options-general.php', 'WCAG Quickfix JS Settings', 'JS WCAG Quickfixes', 'manage_options', 'wcag_quickfix_js_settings', 'wcag_quickfix_settings_js_content' );
}
add_action('admin_menu', 'wcagqf_setup_menu');

/**
 * Register settings.
 *
 * @since  1.0.0
 * @action admin_init
 */
function wcagqf_register_settings() {
	register_setting( 'wcagqf_css_settings_group', 'custom_css_field', WCAGQF_OPTION );
  register_setting( 'wcagqf_js_settings_group', 'custom_js_field', WCAGQF_OPTION );
}
add_action( 'admin_init', 'wcagqf_register_settings' );


/**
* Create admin settings frontent for css
* @since  1.0.0
*/
function wcag_quickfix_settings_css_content(){?>

    <div class="wrap">
        <h2 style="margin-bottom: 1em;">Guelph Digital Services WCAG Quickfixes - Custom CSS</h2>
        <div id="templateside" >
          <p style="margin-left: 1em;">Please use the field below to store site-specific WCAG 2.0 (AA) CSS quickfixes. In the future, these fixes will be taken into account when designing new systems.
          <br><br><strong>WARNING:</strong> Code with errors placed in this section could crash the plugin and even the site. Code should only be placed here that has been tested in staging.</p>
        </div>
        <form method="post" action="options.php">
        <div id="template">
          <div>
            <?php
                settings_fields( 'wcagqf_css_settings_group' );
                echo '<textarea cols="70" rows="30" type="text/css" name="custom_css_field" id="custom_css_field" class="wcagqfcss-content"/>' . get_option( 'custom_css_field' ) . '</textarea>';
                submit_button( __( 'Update Custom CSS', 'gds-wcag-css-quickfixes' ), 'primary', 'submit', true );
            ?>
          </div>
        </div>
        </form>
    </div> <?php
}

/**
* Create admin settings frontent for css
* @since  1.0.0
*/
function wcag_quickfix_settings_js_content(){?>
    <div class="wrap">
        <h2 style="margin-bottom: 1em;" >Guelph Digital Services WCAG Quickfixes - Custom Javascript</h2>
        <div id="templateside" >
          <p style="margin-left: 1em;">Please use the field below to store site-specific WCAG 2.0 (AA) Javascript quickfixes. In the future, these fixes will be taken into account when designing new systems.<br><br><strong>WARNING:</strong> Code with errors placed in this section could crash the plugin and even the site. Code should only be placed here that has been tested in staging.</p>
        </div>
        <form method="post" action="options.php">
          <div id="template">
            <div>
            <?php
                settings_fields( 'wcagqf_js_settings_group' );
                echo '<textarea type="text/js" name="custom_js_field" id="custom_js_field" style="width:100%;" class="wcagqfjs-content"/>' . get_option( 'custom_js_field' ) . '</textarea>';
                submit_button( __( 'Update Custom JS', 'gds-wcag-js-quickfixes' ), 'primary', 'submit', true );
            ?>
            </div>
          </div>
        </form>
    </div> <?php
}
